package com.mavericksoft.stitchx.enums;

public enum OrderStatus {
	
	ORDER_INITIALIZE,
	ORDER_DELETED,
	QR_SCAN_AND_ORDERED,
	ORDER_DELIVER_FROM_SHOP,
	ORDER_DELIVER_AT_COMPANY,
	ORDER_REJECTED,//REJECT BY STITCHX IF CLOTHS ARE DAMMAGED OR ANY OTHER REASON 
	QUALITY_CHECKING,
	DISPATCH_FROM_COMPANY,
	ORDER_DELIVERED

}
